version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.23
    ports:
      - 9411:9411

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    networks:
      - shared-network
    ports:
     - 9090:9090

  db:
    container_name: service_db
    networks:
      - shared-network
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432      

  service-api:
    container_name: service-api
    build:
      context: ../..
      dockerfile: build/Dockerfile
    networks:
      - shared-network
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - zipkin
      - db
