version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:2.23
    ports:
      - 9411:9411

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - shared-network
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  db:
    container_name: service_db
    networks:
      - shared-network
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432      

  service-template:
    container_name: service-template
    build:
      context: ../..
      dockerfile: build/Dockerfile
    networks:
      - shared-network
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - zipkin
      - db

volumes:
  prometheus-data: